name: Deploy to Aliyun OSS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Aliyun CLI
        uses: aliyun/oss-cli@v1.0.0
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Sync Files to OSS
        run: |
          ossutil cp -rf ./ oss://yueyinhuixiang/ --endpoint=oss-cn-hangzhou.aliyuncs.com
          # 使用 ossutil 工具同步本地文件到 OSS Bucket
          # 替换以下参数：
          # your-bucket-name: 你的 Bucket 名称
          # your-bucket-endpoint: 你的 Bucket 地域节点（如 oss-cn-hangzhou.aliyuncs.com）
          ossutil cp -rf ./ oss://your-bucket-name/ --endpoint=your-bucket-endpoint